### ISSUE TITLE
Update to getBrowseGroups docs

### ISSUE THREAD

**Issue by Basia2B** [Constructor-io/constructorio-client-javascript#124]
https://github.com/Constructor-io/constructorio-client-javascript/blob/49d8b500b20c19c482d3962061ecbeb237bd2f40/src/modules/browse.js#L287

`getBrowseGroups` is expecting `fmt_options` to be in camelCase. Suggested update:

```
fmtOptions
```

**Comment by sblaurock** [comment]
Thank you @Basia2B. We'll take a look and get this updated. Appreciate the heads up!

**Comment by sblaurock** [comment]
Should be all set as of https://github.com/Constructor-io/constructorio-client-javascript/pull/126 - thanks again for the heads up!
