### ISSUE TITLE
Incorrect response type for recommendations

### ISSUE THREAD

**Issue by tomdickman** [Constructor-io/constructorio-client-javascript#285]
Hi there,

I am using the Javascript Client to obtain `recommendations` and have noticed that the data resolved from `getRecommendations` in `RecommendationsResponseType['response']['results']` is `Partial<RecommendationsResultType>`, however the data the API response is actually giving me is an array like `Partial<RecommendationsResultType>[]`.

This is causing me type errors when trying to handle the response data as it is actually returned.

This appears to be an issue with the typings in the Client and it means that we can't reliably handle the data and would instead have to type cast it and add our own guards.

Is this intended or is there an issue with our pods?

**Comment by esezen** [comment]
Hello @tomdickman ,

Thanks for raising this issue. I will investigate this tomorrow and get back to you as soon as possible. If there is an issue with the types, we will get them updated.

**Comment by tomdickman** [comment]
Thanks for that @esezen, just for clarity, I believe the type in question I am having trouble with is here https://github.com/Constructor-io/constructorio-client-javascript/blob/master/src/types/recommendations.d.ts#L50

**Comment by esezen** [comment]
@tomdickman the type was incorrect like you mentioned. It has been updated and the changes are live in version `2.37.2` of the library. Please let me know if you run into any issues
