### ISSUE TITLE
Control what data to returned in the response

### ISSUE THREAD

**Issue by comaybay** [Constructor-io/constructorio-client-javascript#319]
I'm using constructorio.browse.getBrowseResults to fetch data of products to display on a page
The response data is very large (~200kb). most of the large content came from results and groups. 

How do I control what content should be returned from the server? For example I want the response to not send property "display_name" of each group but do send property "count".

In the API docs there's a fmtOptions.fields parameter that can be use to control the response format however I have no idea how to actually use it, there are no examples for this parameter.

Can someone help me with this? This really affect performance of our site

**Comment by mocca102** [comment]
@comaybay Appreciate your feedback! We have added fields type in [this PR ](https://github.com/Constructor-io/constructorio-client-javascript/pull/320)

The `fields` parameter specifies an array of metadata fields you want to be returned for each item under `data` object

Also, to further optimize the response payload, you can use VariationsMap to fetch only the relevant variation data. 
`getBrowseResults` accept a variationsMap parameter. You can find more about variations map syntax [here](https://docs.constructor.io/rest_api/variations_mapping/)

The mentioned optimizations apply only to the `results` object and not `groups` array, unfortunately but they should save more in terms of payload size

**Comment by comaybay** [comment]
Ah I see so that how you use it, also `variationsMap` is exactly what I need as well, completely missed that when reading the docs. Thank you!

I would also like to return only a certain fields in `groups` and `facets`, is that possible? is there something similar to `fmtOptions.fields` but for `groups` and `facets`?
