### ISSUE TITLE
RecommendationsParameters doesn't contain preFilterExpression

### ISSUE THREAD

**Issue by cheemingli** [Constructor-io/constructorio-client-javascript#359]
According to the [getRecommendations documentation](https://constructor-io.github.io/constructorio-client-javascript/modules_recommendations.js.html) it is possible to pass the `parameters.preFilterExpression` to the `getRecommendations ` function.

The `RecommendationsParameters ` however doesn't contain the property `preFilterExpression`.

**Comment by esezen** [comment]
Hey @cheemingli ,

Thanks for reporting this. It looks like the types were not updated when we added support for `preFilterExpression` in the recommendations module. I opened a [PR here](https://github.com/Constructor-io/constructorio-client-javascript/pull/360). We will include this in our next release.

**Comment by cheemingli** [comment]
Hi @esezen , 

When updating to `2.59.2` I am facing some challenges with the changes that are part of `2.58.5`: Browse support for filter_match_types.

The required property `filterMatchTypes` was added to the `IBrowseParameters` but is optional for e.g. https://docs.constructor.com/reference/v1-browse-get-browse-results. 
Can you check if `filterMatchTypes` should be required or optional just like the API documentation?

This issue can be closed but hopefully you can follow up my question regarding `filterMatchTypes` in a new ticket.

**Comment by esezen** [comment]
Hey @cheemingli , my apologies for missing your response. Thanks for bringing that to our attention. You are absolutely correct, `filterMatchTypes` should be marked as optional. We fixed it [here](https://github.com/Constructor-io/constructorio-client-javascript/pull/363) and released a new version (`v2.62.1`). I'm closing this issue like you mentioned, feel free to re-open it if you have any further questions about this.
